FROM julia:latest

RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/list/*

RUN julia -e 'import Pkg; Pkg.update()' && \
        julia -e 'import Pkg; Pkg.add("Plots"); using Plots' && \
        julia -e 'import Pkg; Pkg.add("Distributions"); using Distributions' && \
        julia -e 'import Pkg; Pkg.add("IJulia"); using IJulia'

CMD ["julia"]